### ISSUE TITLE
How to setup the license key (in trial and otherwise)

### ISSUE THREAD

**Issue by schusss** [veeso/android-media-player-standalone-library#5]
Hi there, 
I'd like to try the sdk for the player, but I didn't find anywhere where I should set the license key (trial for now) either in the manifest, or somewhere else, it's not described in the documentation.
Also, the app actually crash is the license key is not setup, maybe it should disable all players, but not crash the full app.

"Stopping player instance due to invalid license. To continue check if your Android Package Name is added in the Veeso Dashboard: https://panel.veeso.co/licenses"

**Comment by gabidobo** [comment]
Hi schusss,

You need to go to the URL you can see in the body of the error to set up your license code.
If you don't have an account with us, go to https://panel.veeso.co/users/sign_up, register a new account, then log in and visit the licenses section of your dashboard to get started.

Still, the error should not crash the app - it should, as you said, simply disable the player. I'm leaving this issue open so that @andreimarinescu can have a look at what's going on.

**Comment by schusss** [comment]
I did register, and I have a trial key "b88ab413-0faf-4d1c-925f-bb7..."
But how do I set the key in the android project ? (I don't know how your sdk will grab it)

**Comment by andreimarinescu** [comment]
As long as you've added the Android Package Name from your android manifest
file of your app to the trial license (by tapping the add identifier
button), you don't need to do any additional steps. The player
automatically verifies the package name with the licensing server.

If you've already done this and it is still not working, please let me know
what package name you have used by sending an email to andrei [at] veeplay
[dot] com.

Regarding the crash, kindly provide us with a stack trace, we'll have a
look a.s.a.p. You should know that this exception is only triggered by an
invalid license. Any other issues, such as networking or server unavailable
will not trigger an invalid license exception.

**Comment by schusss** [comment]
Thx, I'll try now, and let you know

**Comment by schusss** [comment]
ok the license is not a problem anymore, thx
