### ISSUE TITLE
Question: How to set custom User-Agent

### ISSUE THREAD

**Issue by sch0057k** [veeso/android-media-player-standalone-library#9]
Hello,

is there some sort of guide or example on how to set a custom User-Agent in the Android version? I did not find any information on that.

The [product sheet](http://veeplay.com/VeeplayProductSheet.pdf) states that this is possible via configuration.

> VMAP and VAST Player Configuration Settings
> ○custom User-Agent setting, to emulate specific browsers and support features like
> frequency capping

This would be greatly appreciated regarding the March update of the IAB Spiders & Bots list.

**Comment by andreimarinescu** [comment]
Hey, Kevin,

The issue is most certainly out of date now, but leaving a reply here in case the question will come up in the future. The proper method of setting the user agent used for making VMAP or VAST requests is to call `APSMediaPlayer.getInstance().setUserAgent("UA-String")` when initializing the player.

Please contact our support team directly in case you need any assistance with our SDK in the future.

Kind regards,

Andrei
